nav:
  Home: /
  About: /about/
  Projects: https://github.com/darksmile

projects_url: https://github.com/darksmile

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 60
        url: /images/logo.png
        position_top: -8px
        position_right: 15px
        position_bottom: 0
        position_left: 0
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/darksmile/
        twitter: https://twitter.com/_darksmile
        facebook: https://www.facebook.com/mykyta.shirin
        linkedin: linkedin.com/in/mshyrin
    post_count: 500
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
